---
name: 'libfuse ABI check against previous major release'

on:
  push:
    branches:
      - master
      - 'fuse-[0-9]+.[0-9]+*'  # This will match branches like 3.17, 3.18, 4.0, etc.
  pull_request:
    branches:
      - master
      - 'fuse-[0-9]+.[0-9]+*'
permissions:
  contents: read

jobs:
  abi:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get -y install abigail-tools clang gcc liburing-dev libnuma-dev

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: current
          fetch-depth: 0  # Fetch all history and tags

      - name: Determine previous major release tag
        id: prev_release
        run: |
          cd current
          chmod +x .github/workflows/find_previous_release_tag.sh
          PREV_TAG=$(.github/workflows/find_previous_release_tag.sh)
          echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: previous
          ref: ${{ steps.prev_release.outputs.prev_tag }}

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.12'

      - name: Build current
        working-directory: current
        run: |
          pip install -r requirements.txt
          meson setup build --buildtype=debug
          meson compile -C build

      - name: Build previous
        working-directory: previous
        run: |
          echo "Previous release tag: ${{ steps.prev_release.outputs.prev_tag }}"
          echo "Commit-id of previous release: $(git show HEAD)"
          pip install -r requirements.txt
          meson setup build --buildtype=debug
          meson compile -C build

      - name: Run abidiff
        run: abidiff
          --no-added-syms
          --suppressions current/.github/workflows/abidiff_suppressions.abignore
          --headers-dir1 previous/include/
          --headers-dir2 current/include/
          previous/build/lib/libfuse3.so
          current/build/lib/libfuse3.so
